- name: Cluster Create
  hosts: all
  become_user: demo
  become: yes
  gather_facts: no
  vars:
    ansible_connection: "ssh"
    ansible_port: 22
    ansible_user: "demo"
    ansible_ssh_pass: "AaBb54321@@"
    ansible_sudo_pass: "AaBb54321@@"
    ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
    clustercommand: "redis-cli -a VP53tHYgfxcHRLFDtuLGnmhKXRuUafaN --cluster create 10.100.65.201:7001 10.100.65.202:7001 10.100.65.203:7001 10.100.65.204:7001 10.100.65.205:7001 10.100.65.206:7001 --cluster-replicas 1 --cluster-yes"
  tasks:
        - name: Create
          command:  "{{ clustercommand }}"
          ignore_errors: yes
